services:
  app:
      image: ws_v2.0
      container_name: ws_app
      ports:
        - "8080:8080"
      volumes:
        - ./db:/app/db
      environment:
        - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
        - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
        - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
        - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}