services:
  app:
      image: ws:v1.0
      container_name: ws_app
      ports:
        - "8080:8080"
      volumes:
        - ./data:/app/data
      environment:
        - SPRING_DATASOURCE_URL=jdbc:sqlite:/app/data/waybill_shaper.db