services:
  app:
      image: ws:v1.0
      container_name: ws_app
      ports:
        - "8080:8080"
      env_file:
        - .env
      environment:
        SPRING_DATASOURCE_URL: ${DATASOURCE_URL}
        SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
        SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
        TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      depends_on:
        - postgres
      networks:
        - ws-network

  postgres:
    image: postgres:latest
    container_name: ws_db
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${SPRING_DATASOURCE_USERNAME}
      POSTGRES_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    networks:
      - ws-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $SPRING_DATASOURCE_USERNAME -d $POSTGRES_DB || exit 1" ]
      interval: 10s
      timeout: 5s
      start_period: 5s
      retries: 5

networks:
  ws-network:
    driver: bridge